# Generated by Django 5.1.6 on 2025-03-07 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgaffsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default='Student Accommodation', on_delete=django.db.models.deletion.CASCADE, to='glasgowgaffsapp.location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
