# Generated by Django 5.1.6 on 2025-03-07 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User
admin = User.objects.get(username="team8b")

class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgaffsapp', '0002_event_location_alter_event_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default=admin.id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
