# Generated by Django 5.1.6 on 2025-03-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgaffsapp', '0006_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=1),
        ),
    ]
