# Generated by Django 5.1.6 on 2025-03-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgaffsapp', '0007_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
